test: cockpit-pcp is deprecated - use cockpit-composer
linux-system-roles/cockpit pull request #181
Opened 2024-11-15 17:43 UTC by richm

The tests_packages_full test is failing on el9.6 and later - cockpit-pcp
is missing - use cockpit-composer instead which seems to be available
on all platforms.

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

2024-11-15 18:23 UTC, richm commented
[citest]

2024-11-16 01:58 UTC, richm commented
[citest]

2024-11-16 07:48 UTC, martinpitt commented
OK -- Note that you will have to replace the "cockpit-pcp" fallback with something else eventually, it's gone [in current Ubuntu version](https://launchpad.net/ubuntu/+source/cockpit/328-1) as well.

2024-11-16 17:12 UTC, richm commented
> OK -- Note that you will have to replace the "cockpit-pcp" fallback with something else eventually, it's gone [in current Ubuntu version](https://launchpad.net/ubuntu/+source/cockpit/328-1) as well.

Ok - I guess we'll need to do that when we add a CI test for `Integration tests / ubuntu (ubuntu-24.04)`

2024-11-16 17:12 UTC, richm commented
[citest]

2024-11-18 15:17 UTC, spetrosi commented
[citest bad]

2024-11-18 17:52 UTC, spetrosi submitted a review, later dismissed

2024-11-19 08:42 UTC, martinpitt requested changes
Argh! I did a review three days ago, but apparently actually *sending* it failed. Sorry! (I was already wondering why I was being ignored..)

2024-11-19 13:54 UTC, richm commented on tests/tests_packages_full.yml
> +              else 'ansible-pcp' }}"
see latest commit

2024-11-19 14:34 UTC, martinpitt commented
@richm weird -- it does exist in 22.04, 24.04, and latest: https://launchpad.net/ubuntu/+source/cockpit-podman

2024-11-19 14:38 UTC, martinpitt commented
I'm not sure I understand this -- what actually tells the role to install cockpit-podman? Shouldn't that be [here](https://github.com/linux-system-roles/cockpit/pull/181/files#diff-52710118a650ecc27838442206f52cdfea306ed911eb459f8a4fee6621ebf224R13)? As far as I can see, this only changes the check after the role ran, but not the role invocation itself?

2024-11-19 14:57 UTC, richm commented
> I'm not sure I understand this -- what actually tells the role to install cockpit-podman?

The test tells the cockpit role to install all packages specified in `__cockpit_packages_full`. 

On RedHat family https://github.com/linux-system-roles/cockpit/blob/main/vars/RedHat-10.yml#L24
and by default if no OS customization is specified https://github.com/linux-system-roles/cockpit/blob/main/vars/default.yml#L16
the role installs `cockpit-*`

> Shouldn't that be [here](https://github.com/linux-system-roles/cockpit/pull/181/files#diff-52710118a650ecc27838442206f52cdfea306ed911eb459f8a4fee6621ebf224R13)?

Yes.

> As far as I can see, this only changes the check after the role ran, but not the role invocation itself?

Right.  So the problem is that installing `cockpit-*` on Ubuntu is not pulling in the `cockpit-podman` package.

> 
> **Update**: That should happen through
> 
> ```yaml
> __cockpit_packages_full:
>   - cockpit-*
> ```
> 
> So this feels like a bug.

2024-11-19 15:01 UTC, richm commented
yes, this is a bug - note this from the Ubuntu log:
```
TASK [linux-system-roles.cockpit : Set version specific variables] *************
task path: /home/runner/work/cockpit/cockpit/tests/roles/linux-system-roles.cockpit/tasks/set_vars.yml:32
ok: [localhost] => (item=/home/runner/work/cockpit/cockpit/tests/roles/linux-system-roles.cockpit/vars/Debian.yml) => {"ansible_facts": {"__cockpit_packages": {"default": "{{ __cockpit_packages_minimal + __cockpit_packages_default }}", "full": "{{ __cockpit_packages_minimal + __cockpit_packages_default + __cockpit_packages_full }}", "minimal": "{{ __cockpit_packages_minimal }}"}, "__cockpit_packages_default": ["cockpit", "cockpit-networkmanager", "cockpit-packagekit", "cockpit-storaged"], "__cockpit_packages_full": ["cockpit-doc", "cockpit-machines", "cockpit-pcp"], "__cockpit_packages_minimal": ["cockpit-system", "cockpit-ws"]}, "ansible_included_var_files": ["/home/runner/work/cockpit/cockpit/tests/roles/linux-system-roles.cockpit/vars/Debian.yml"], "ansible_loop_var": "item", "changed": false, "item": "/home/runner/work/cockpit/cockpit/tests/roles/linux-system-roles.cockpit/vars/Debian.yml"}
```
It is using **Debian** specific values on **Ubuntu**

2024-11-19 15:05 UTC, richm commented
@martinpitt ah - because Ubuntu is in Debian os_family and because there is a Debian.yml vars file, this code pulls in those variable definitions for Debian on Ubuntu - https://github.com/linux-system-roles/cockpit/blob/main/tasks/set_vars.yml#L32

so what should we do here?  Should I create a vars/Ubuntu.yml which uses `cockpit-*` for `__cockpit_packages_full`?  Also note that doing so would be unrelated to this PR, so I would do that in a separate PR.

2024-11-19 15:18 UTC, martinpitt commented
That seems right in general -- Ubuntu as a derivative of Debian should be similar enough to Debian to not warrant another copy I think. So is the problem that https://github.com/linux-system-roles/cockpit/blob/main/vars/Debian.yml#L10 doesn't support a "cockpit-*" glob?

As a minimal fix for *this* PR you may perhaps use "cockpit-machines"? That exists everywhere aside from RHEL 7 (not sure if you still care about that), and it's part of the Debian __full definition. And perhaps in a follow-up add cockpit-podman there, if the globbing doesn't work?

Thanks!

2024-11-19 15:27 UTC, richm commented
> That seems right in general -- Ubuntu as a derivative of Debian should be similar enough to Debian to not warrant another copy I think. So is the problem that https://github.com/linux-system-roles/cockpit/blob/main/vars/Debian.yml#L10 doesn't support a "cockpit-*" glob?

correct - and I don't know enough about Debian to know if it should be `cockpit-*`, or a discrete list of packages.

> 
> As a minimal fix for _this_ PR you may perhaps use "cockpit-machines"? That exists everywhere aside from RHEL 7 (not sure if you still care about that), and it's part of the Debian __full definition. And perhaps in a follow-up add cockpit-podman there,

Where is "there"?  In Debian.yml in the `__cockpit_packages_full` list?

> if the globbing doesn't work?

ok - but we don't have testing on Debian, so I don't know if `cockpit-*` will work for all Debian os_family platforms.

> 
> Thanks!

2024-11-19 15:44 UTC, martinpitt commented
> Where is "there"? In Debian.yml in the __cockpit_packages_full list?

Yes, sorry. 

> I don't know if cockpit-* will work for all Debian os_family platforms.

This should largely be a function of Ansible and apt/python-apt, not of the specific distro (that seems highly unlikely to patch in a derivative), so if it works on Debian stable or Ubuntu 22.04, it ought to work everywhere.

2024-11-19 15:55 UTC, richm commented
> > Where is "there"? In Debian.yml in the __cockpit_packages_full list?
> 
> Yes, sorry.
> 
> > I don't know if cockpit-* will work for all Debian os_family platforms.
> 
> This should largely be a function of Ansible and apt/python-apt, not of the specific distro (that seems highly unlikely to patch in a derivative), so if it works on Debian stable or Ubuntu 22.04, it ought to work everywhere.

ok - I'll do that in a separate PR

2024-11-19 15:55 UTC, richm commented
[citest]

2024-11-19 16:34 UTC, martinpitt approved these changes
Thanks! LGTM, if that goes green.

2024-11-19 16:35 UTC, martinpitt commented
(although it could just use c-machines everywhere and be simplified, but I don't mind much)

2024-11-19 16:53 UTC, richm commented
[citest]

2024-11-19 17:15 UTC, merged